
server:
  port: 8443
  servlet:
    context-path: /spring-saml
  ssl:
    enabled: true
    key-alias: spring
    key-store: "classpath:saml/keystore.jks"
    key-store-password: secret

spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            identityprovider:
              entity-id: ""
              verification.credentials:
                - certificate-location: "classpath:saml/okta.cert"
              singlesignon.url: ""
              singlesignon.sign-request: false